# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Fabric Properties - Minecraft 1.21.1
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.16.0-alpha.13
java_version=25

# Mod Properties
mod_version=1.0.0
maven_group=me.seyit
archives_base_name=particleplus

# Dependencies
fabric_version=0.144.3+26.1
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
