# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Fabric Properties - Minecraft 1.21.1
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
java_version=25

# Mod Properties
mod_version=1.0.0
maven_group=me.seyit
archives_base_name=particleplus

# Dependencies
fabric_version=0.152.2+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0-beta.2
